version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    # depends_on:
    #   - db

#   db:
#     image: postgres:13
#     environment:
#       POSTGRES_USER: yourusername
#       POSTGRES_PASSWORD: yourpassword
#       POSTGRES_DB: yourdbname
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
